### ISSUE TITLE
Getting This error while fetching hashtag

### ISSUE THREAD

**Issue by rajendraptl-itpath** [instabotai/tiktok-api#14]
Py Code : 
from tiktok_bot import TikTokBot

bot = TikTokBot()

my_feed = bot.search_posts_by_hashtag("macarenachallenge", count=50)

print(my_feed)

Searching hashtags:   0%|                                                                                                                                                                                              | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "tiktok.py", line 7, in <module>
    my_feed = bot.search_posts_by_hashtag("macarenachallenge", count=50)
  File "/var/www/html/tiktok-demo/tiktok_bot/bot/bot.py", line 49, in search_posts_by_hashtag
    tags = self.search_hashtags(keyword=hashtag_name, count=1)
  File "/var/www/html/tiktok-demo/tiktok_bot/bot/bot.py", line 42, in search_hashtags
    hashtags_search = self.api.search_hashtags(keyword=keyword, count=count)
  File "/var/www/html/tiktok-demo/tiktok_bot/api/api.py", line 224, in search_hashtags
    response = self._search_hashtags(search_request)
  File "/var/www/html/tiktok-demo/tiktok_bot/api/api.py", line 210, in _search_hashtags
    hashtag_search = HashtagSearchResponse(**response.json())
  File "/var/www/html/tiktok-demo/venv/lib/python3.6/site-packages/httpx/models.py", line 930, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by steffanjensen** [comment]
was it fixed ?
